### ISSUE TITLE
Bybit: error when subscribe to an option. No error when a put-strike or a call-strike already selected

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#373] opened 2024-10-09 15:51 UTC
2024-10-09 15:48:18,374 - functions - INFO - Bybit - Subscription to BTC-26SEP25_series. Waiting for confirmation from Bybit.
2024-10-09 15:48:18,375 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-10-09 15:48:19,378 - websocket - INFO - Websocket connected
2024-10-09 15:48:19,378 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-10-09 15:48:19,379 - api.bybit.ws - INFO - Bybit - ws subscription - Orderbook - channel - option ['BTC-26SEP25-20000-C', 'BTC-26SEP25-40000-C', 'BTC-26SEP25-50000-C', 'BTC-26SEP25-60000-C', 'BTC-26SEP25-70000-C', 'BTC-26SEP25-75000-C', 'BTC-26SEP25-80000-C', 'BTC-26SEP25-85000-C', 'BTC-26SEP25-90000-C', 'BTC-26SEP25-95000-C', 'BTC-26SEP25-100000-C', 'BTC-26SEP25-110000-C', 'BTC-26SEP25-120000-C', 'BTC-26SEP25-130000-C', 'BTC-26SEP25-150000-C', 'BTC-26SEP25-170000-C', 'BTC-26SEP25-180000-C', 'BTC-26SEP25-200000-C', 'BTC-26SEP25-220000-C', 'BTC-26SEP25-240000-C', 'BTC-26SEP25-20000-P', 'BTC-26SEP25-40000-P', 'BTC-26SEP25-50000-P', 'BTC-26SEP25-60000-P', 'BTC-26SEP25-70000-P', 'BTC-26SEP25-75000-P', 'BTC-26SEP25-80000-P', 'BTC-26SEP25-85000-P', 'BTC-26SEP25-90000-P', 'BTC-26SEP25-95000-P', 'BTC-26SEP25-100000-P', 'BTC-26SEP25-110000-P', 'BTC-26SEP25-120000-P', 'BTC-26SEP25-130000-P', 'BTC-26SEP25-150000-P', 'BTC-26SEP25-170000-P', 'BTC-26SEP25-180000-P', 'BTC-26SEP25-200000-P', 'BTC-26SEP25-220000-P', 'BTC-26SEP25-240000-P']
2024-10-09 15:48:19,380 - api.bybit.ws - INFO - Bybit - ws subscription - Ticker - channel - option ['BTC-26SEP25-20000-C', 'BTC-26SEP25-40000-C', 'BTC-26SEP25-50000-C', 'BTC-26SEP25-60000-C', 'BTC-26SEP25-70000-C', 'BTC-26SEP25-75000-C', 'BTC-26SEP25-80000-C', 'BTC-26SEP25-85000-C', 'BTC-26SEP25-90000-C', 'BTC-26SEP25-95000-C', 'BTC-26SEP25-100000-C', 'BTC-26SEP25-110000-C', 'BTC-26SEP25-120000-C', 'BTC-26SEP25-130000-C', 'BTC-26SEP25-150000-C', 'BTC-26SEP25-170000-C', 'BTC-26SEP25-180000-C', 'BTC-26SEP25-200000-C', 'BTC-26SEP25-220000-C', 'BTC-26SEP25-240000-C', 'BTC-26SEP25-20000-P', 'BTC-26SEP25-40000-P', 'BTC-26SEP25-50000-P', 'BTC-26SEP25-60000-P', 'BTC-26SEP25-70000-P', 'BTC-26SEP25-75000-P', 'BTC-26SEP25-80000-P', 'BTC-26SEP25-85000-P', 'BTC-26SEP25-90000-P', 'BTC-26SEP25-95000-P', 'BTC-26SEP25-100000-P', 'BTC-26SEP25-110000-P', 'BTC-26SEP25-120000-P', 'BTC-26SEP25-130000-P', 'BTC-26SEP25-150000-P', 'BTC-26SEP25-170000-P', 'BTC-26SEP25-180000-P', 'BTC-26SEP25-200000-P', 'BTC-26SEP25-220000-P', 'BTC-26SEP25-240000-P']
2024-10-09 15:48:19,984 - functions - INFO - Bybit - Added subscription to BTC-26SEP25_series.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/241009/main.py", line 14, in refresh
    connect.refresh()
  File "/home/rmn/241009/connect.py", line 315, in refresh
    Function.refresh_on_screen(ws, utc=utc)
  File "/home/rmn/241009/functions.py", line 783, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/241009/functions.py", line 1230, in refresh_tables
    Function.display_options_desk(self)
  File "/home/rmn/241009/functions.py", line 1042, in display_options_desk
    instrument.bidSize,
AttributeError: 'Instrument' object has no attribute 'bidSize'

**Comment by evgrmn** [comment] 2024-10-09 16:26
You probably subscribed but still haven't received data from the websocket. The issue is resolved by setting values ​​like bidSize to default "-". See commit fc6c61e.

**Closed as completed** 2024-10-10 17:18 UTC
